label = "Español"
locale = "es-es"
weight = 2
title = "K'drian A. Vega"

[params]
  displayName = "ES"
  logo = "/img/logo.png"
  disableTextInHeader = true
  
[params.author]
   name = "K'drian Antonio Vega"
   image = "/img/profile.jpg"
   headline = "Programador, Tutor de Ciencia de Computación, & Técnico de Sonido"
   links = [
    { email = "mailto:kdrianvega@gmail.com"},
    { github = "https://github.com/csku25" },
    { linkedin = "https://linkedin.com/in/k-drian-vega-124350264" },
   ]

[[menus.main]]
  name = "Proyectos"
  pageRef = "projects"
  weight = 10

[[menus.main]]
  name = "Currículum"
  pageRef = "resume"
  weight = 20

[[menus.main]]
  name = "Sobre Mí"
  pageRef = "about_me"
  weight = 30
